# -*- coding: utf-8 -*-
__title__ = "300"
__author__ = ""
__context__ = 'Selection'
__doc__ = """Klar fÃ¶r utvÃ¤rdering
Objektet Ã¤r vidareutvecklat fÃ¶r produktion och anbud. Mindre justeringar kan fÃ¶rekomma. Objektet Ã¤r placerat i plan, profil och hÃ¶jd. Objektet Ã¤r nu i 3D. Tekniska data som geometri, form och toleranser kan vara definierade.

Sets the MMI parameter value to 300 on selected elements.
Based on MMI veilederen: https://mmi-veilederen.no/?page_id=85"""

from Autodesk.Revit.DB import Transaction, ElementId, FilteredElementCollector, BuiltInCategory
from pyrevit import revit, DB, forms

# Get the current document and selection
doc = revit.doc
selection = revit.get_selection()

if not selection:
    forms.alert('Please select at least one element.', exitscript=True)

# Start a transaction
t = Transaction(doc, 'Set MMI Parameter to 300')
t.Start()

try:
    # Set MMI parameter for each selected element
    for element_id in selection.element_ids:
        element = doc.GetElement(element_id)
        if element:
            # Try to set the parameter value
            param = element.LookupParameter('MMI')
            if param and not param.IsReadOnly:
                param.Set('300')
            else:
                print("Could not set MMI parameter on element {}".format(element_id))
    
    # No success alert as requested
except Exception as e:
    print("Error: {}".format(e))
    forms.alert('Error: {}'.format(e), title='Error')
finally:
    # Commit the transaction
    t.Commit()

# --------------------------------------------------
# ðŸ’¡ pyRevit with VSCode: Use pyrvt or pyrvtmin snippet
# ðŸ“„ Template has been developed by Baptiste LECHAT and inspired by Erik FRITS. 